name: WordFreqApp
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.WordFreqApp
    DEVELOPMENT_TEAM: Z9D957576J
    SWIFT_VERSION: 5.9
    MACOSX_DEPLOYMENT_TARGET: 13.0
    CODE_SIGN_STYLE: Automatic
  configs:
    Release:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
targets:
  WordFreqApp:
    type: application
    platform: macOS
    sources:
      - path: WordFreqApp/Sources/WordFreqApp
      - path: WordFreqApp/Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.johnbrady.WordFreq
        PRODUCT_NAME: WordFreqApp
        INFOPLIST_KEY_CFBundleDisplayName: WordFreqApp
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        GENERATE_INFOPLIST_FILE: YES
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        ENABLE_HARDENED_RUNTIME: YES
      configs:
        Debug:
          CODE_SIGN_IDENTITY[sdk=macosx*]: "Apple Development"
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Developer ID Application"
          CODE_SIGN_IDENTITY[sdk=macosx*]: "Developer ID Application"
          PROVISIONING_PROFILE_SPECIFIER: ""
          CODE_SIGN_ENTITLEMENTS: WordFreqApp/Config/Release.entitlements
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
          ENABLE_HARDENED_RUNTIME: YES
          OTHER_CODE_SIGN_FLAGS: "--timestamp"
    scheme:
      testTargets:
        - WordFreqAppTests
  WordFreqAppTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: WordFreqAppTests
    dependencies:
      - target: WordFreqApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
